pipeline {
    agent any
    stages {

        stage('Checkout SCM') {
            steps {
                git url: 'git@github.com:mnorm88/multithreading-example-1.git'
            }
        }
        stage('Build') {
            steps {
                //
            }
        }
        stage('Test') {
            steps {
                //
            }
        }
        stage('Deploy') {
            steps {
                //
            }
        }
    }
}
